title: Floris Gorter - Homepage
page-top-title: Floris Gorter
top-section-bg-text: System Security Researcher
home-subtitle: Floris Gorter
copyright-text: '&copy; Floris Gorter 2024. All Rights Reserved.'
