title: Floris Gorter - Homepage
page-top-title: Floris Gorter
top-section-bg-text: Memory Safety Research
home-subtitle: Floris Gorter
copyright-text: '&copy; Floris Gorter 2025. All Rights Reserved.'
